/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import AppPackage.AnimationClass;

/**
 *
 * @author Joshua
 */
public class TelaWelcome extends javax.swing.JFrame {

    AnimationClass sc = new AnimationClass();

    /**
     * Creates new form TelaWelcome
     */
    public TelaWelcome() {
        initComponents();
        setLocationRelativeTo(null);
        slideShow();
    }

    public void slideShow() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                int nb = 0;
                try {
                    while (true) {
                        switch (nb) {
                            case 0:
                                Thread.sleep(1000);
                                sc.jLabelXLeft(0, -500, 12, 10, img1);
                                sc.jLabelXLeft(500, 0, 12, 10, img2);
                                sc.jLabelXLeft(1000, 500, 12, 10, img3);
                                nb++;
                            case 1:
                                Thread.sleep(1000);
                                sc.jLabelXLeft(-500, -1000, 12, 10, img1);
                                sc.jLabelXLeft(0, -500, 12, 10, img2);
                                sc.jLabelXLeft(500, 0, 12, 10, img3);
                                nb++;
                            case 2:
                                Thread.sleep(1000);
                                sc.jLabelXLeft(-1000, -500, 12, 10, img1);
                                sc.jLabelXLeft(-500, 0, 12, 10, img2);
                                sc.jLabelXLeft(500, 0, 12, 10, img3);
                                nb++;
                            case 3:
                                Thread.sleep(1000);
                                sc.jLabelXLeft(-500, 0, 12, 10, img1);
                                sc.jLabelXLeft(0, 500, 12, 10, img2);
                                sc.jLabelXLeft(500, 1000, 12, 10, img3);
                                nb = 0;
                        }
                    }
                } catch (Exception e) {
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFarmacia = new javax.swing.JLabel();
        progressB = new javax.swing.JProgressBar();
        lblProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setForeground(new java.awt.Color(204, 204, 204));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome in Mark");
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 190, -1, -1));

        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lei.jpg"))); // NOI18N
        img1.setToolTipText("");
        left.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/jovem-mulher.jpg"))); // NOI18N
        img2.setToolTipText("");
        left.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ph1.jpg"))); // NOI18N
        img3.setToolTipText("");
        left.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        container.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/linkedin_30px.png"))); // NOI18N
        right.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/angola_30px.png"))); // NOI18N
        right.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/google_30px.png"))); // NOI18N
        right.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 30, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/facebook_30px.png"))); // NOI18N
        right.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 30, 30));

        lblFarmacia.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        lblFarmacia.setForeground(new java.awt.Color(0, 153, 51));
        lblFarmacia.setText("Farmácia Mark");
        right.add(lblFarmacia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 25));

        progressB.setBackground(new java.awt.Color(51, 51, 51));
        right.add(progressB, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 480, 60, 6));

        lblProgress.setForeground(new java.awt.Color(153, 0, 0));
        lblProgress.setText("0%");
        right.add(lblProgress, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        container.add(right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 500));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 500));

        setBounds(0, 0, 1000, 500);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        TelaWelcome p = new TelaWelcome();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                p.setVisible(true);
            }
        });

        TelaLogin telaLogin = new TelaLogin();

        try {
            for (int i = 0; i <= 100; i++) {
                Thread.sleep(100);
                p.progressB.setValue(i);
                p.lblProgress.setText(String.valueOf(i) + "%");
                if (i == 100) {
                    p.setVisible(false);
                    p.dispose();
                }
            }
        } catch (InterruptedException ex) {
            // Logger.getLogger(TelaWelcome.class.getName()).log(Level.SEVERE, null, ex);
        }

        telaLogin.setVisible(true);
        p.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFarmacia;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JPanel left;
    private javax.swing.JProgressBar progressB;
    private javax.swing.JPanel right;
    // End of variables declaration//GEN-END:variables
}
