/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import AppPackage.AnimationClass;
import conexao.ConexaoMySql;
import controller.ControllerFarmaceutico;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModelFarmaceutico;
import utilitarios.ConvertDatas;
import java.sql.*;

/**
 *
 * @author Joshua
 */
public class TelaUsuario extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    ModelFarmaceutico modelFarmaceutico = new ModelFarmaceutico();
    ControllerFarmaceutico controllerFarmaceutico = new ControllerFarmaceutico();
    ConvertDatas convertDatas = new ConvertDatas();
    AnimationClass ac  = new AnimationClass();
    String sexo;
    FileInputStream arquivoFoto;
    
    /**
     * Creates new form TelaExemplo
     */
    public TelaUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        slideFrames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBody = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JLabel();
        btnMinimizar = new javax.swing.JLabel();
        lblCadFarmaceutico = new javax.swing.JLabel();
        lblCadUsuario = new javax.swing.JLabel();
        desktopFarmaceutico = new javax.swing.JDesktopPane();
        frameFarmaceutico = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCompleto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblSexo = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        txtMasculino = new javax.swing.JRadioButton();
        txtFemenino = new javax.swing.JRadioButton();
        lblNomeCompleto = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        txtEstadoCivil = new componentes.UJComboBox();
        lblEstadoUsuario = new javax.swing.JLabel();
        txtStatus = new componentes.UJComboBox();
        txtAnoNasc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblAnoNascimento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showFarmaceutico = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnSelectImag = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnMenu = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        frameUsuario = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtUser4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtUser6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        uJComboBox3 = new componentes.UJComboBox();
        jLabel22 = new javax.swing.JLabel();
        uJComboBox4 = new componentes.UJComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnEditar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnNovo1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        btnRemover1 = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel23 = new javax.swing.JLabel();
        uJComboBox5 = new componentes.UJComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBody.setBackground(new java.awt.Color(204, 204, 204));
        pnlBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/exit_macos_20px.png"))); // NOI18N
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/minimized_macos_20px.png"))); // NOI18N
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMinimizarMousePressed(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 10, -1, -1));

        lblCadFarmaceutico.setForeground(new java.awt.Color(102, 102, 102));
        lblCadFarmaceutico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/new_job_35px.png"))); // NOI18N
        lblCadFarmaceutico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadFarmaceutico.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCadFarmaceuticoMouseMoved(evt);
            }
        });
        lblCadFarmaceutico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadFarmaceuticoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadFarmaceuticoMouseExited(evt);
            }
        });
        jPanel1.add(lblCadFarmaceutico, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 190, 40, 40));

        lblCadUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/customer_35px.png"))); // NOI18N
        lblCadUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCadUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseMoved(evt);
            }
        });
        lblCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCadUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(lblCadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 140, 40, 40));

        pnlBody.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 600));

        desktopFarmaceutico.setBackground(new java.awt.Color(51, 0, 255));
        desktopFarmaceutico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        frameFarmaceutico.setVisible(true);
        frameFarmaceutico.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                frameFarmaceuticoInternalFrameOpened(evt);
            }
        });
        frameFarmaceutico.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Farmaceutico");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        txtNomeCompleto.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeCompleto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomeCompleto.setForeground(new java.awt.Color(73, 181, 172));
        txtNomeCompleto.setBorder(null);
        jPanel2.add(txtNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/name_25px.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator1.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 300, 10));

        lblSexo.setText("Sexo");
        jPanel2.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 300, -1, -1));

        txtTelefone.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(73, 181, 172));
        txtTelefone.setBorder(null);
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/phone_25px.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator2.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, 10));

        lblTelefone.setText("Telefone");
        jPanel2.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 180, -1, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(73, 181, 172));
        txtEmail.setBorder(null);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 270, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Email_25px.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator3.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 10));

        lblEmail.setText("Email");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 240, -1, -1));

        txtMasculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(txtMasculino);
        txtMasculino.setText("Masculino");
        txtMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasculinoActionPerformed(evt);
            }
        });
        jPanel2.add(txtMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        txtFemenino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(txtFemenino);
        txtFemenino.setText("Femenino");
        txtFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFemeninoActionPerformed(evt);
            }
        });
        jPanel2.add(txtFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        lblNomeCompleto.setText("Nome Completo");
        jPanel2.add(lblNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, 120, -1, -1));

        lblEstadoCivil.setText("Estado Civil");
        jPanel2.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        txtEstadoCivil.setBackground(new java.awt.Color(255, 255, 255));
        txtEstadoCivil.setForeground(new java.awt.Color(73, 181, 172));
        txtEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Casado", "Solteiro", "Divorciado", "Divorciada", "Viúvo", "Viúva" }));
        jPanel2.add(txtEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 300, 30));

        lblEstadoUsuario.setText("Estado do Usuário");
        jPanel2.add(lblEstadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setForeground(new java.awt.Color(73, 181, 172));
        txtStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Habilitado", "Desabilitado" }));
        jPanel2.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 300, 30));

        txtAnoNasc.setBackground(new java.awt.Color(255, 255, 255));
        txtAnoNasc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtAnoNasc.setForeground(new java.awt.Color(73, 181, 172));
        txtAnoNasc.setBorder(null);
        jPanel2.add(txtAnoNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 270, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/date_13_25px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator4.setForeground(new java.awt.Color(73, 181, 172));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 300, 10));

        lblAnoNascimento.setText("Ano de Nascimento");
        jPanel2.add(lblAnoNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 240, -1, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        showFarmaceutico.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        showFarmaceutico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Expresso POS", "Kenya", null, null, null, null, null, null},
                {null, "ROM Gen", "US", null, null, null, null, null, null},
                {null, "Text Ed", "UK", null, null, null, null, null, null},
                {null, "Mola Con", "China", null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Completo", "Telefone", "Email", "Ano de Nascimento", "Idade", "Sexo", "Estado Civil", "Condição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showFarmaceutico.setGridColor(new java.awt.Color(255, 255, 255));
        showFarmaceutico.setRowHeight(22);
        jScrollPane1.setViewportView(showFarmaceutico);
        if (showFarmaceutico.getColumnModel().getColumnCount() > 0) {
            showFarmaceutico.getColumnModel().getColumn(0).setMinWidth(30);
            showFarmaceutico.getColumnModel().getColumn(0).setPreferredWidth(30);
            showFarmaceutico.getColumnModel().getColumn(0).setMaxWidth(30);
            showFarmaceutico.getColumnModel().getColumn(5).setMinWidth(50);
            showFarmaceutico.getColumnModel().getColumn(5).setMaxWidth(50);
            showFarmaceutico.getColumnModel().getColumn(5).setHeaderValue("Idade");
            showFarmaceutico.getColumnModel().getColumn(6).setHeaderValue("Sexo");
            showFarmaceutico.getColumnModel().getColumn(7).setHeaderValue("Estado Civil");
            showFarmaceutico.getColumnModel().getColumn(8).setHeaderValue("Condição");
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 710, 160));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_25px.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 95, 35));

        btnSelectImag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/download_25px.png"))); // NOI18N
        btnSelectImag.setText("Imagen");
        btnSelectImag.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSelectImag.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectImag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectImagActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelectImag, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 95, 35));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/new_25px.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 95, 35));

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/save_25px.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 95, 35));

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_25px.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRemover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 95, 35));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu_25px.png"))); // NOI18N
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        jPanel2.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 26));

        txtImagen.setEditable(false);
        txtImagen.setBackground(new java.awt.Color(255, 255, 255));
        txtImagen.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        txtImagen.setForeground(new java.awt.Color(102, 102, 102));
        txtImagen.setBorder(null);
        txtImagen.setEnabled(false);
        jPanel2.add(txtImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 710, 30));

        jLabel24.setText("Código");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_25px.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 95, 35));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(204, 0, 0));
        txtCodigo.setText("12");
        txtCodigo.setBorder(null);
        txtCodigo.setEnabled(false);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 30));

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("Foto");
        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, 110));

        frameFarmaceutico.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 770, 600));

        desktopFarmaceutico.add(frameFarmaceutico, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -20, 960, 640));

        frameUsuario.setVisible(false);
        frameUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 0));
        jLabel13.setText("Usuário");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txtUser4.setEditable(false);
        txtUser4.setBackground(new java.awt.Color(73, 181, 172));
        txtUser4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUser4.setForeground(new java.awt.Color(204, 0, 0));
        txtUser4.setText("12");
        txtUser4.setBorder(null);
        txtUser4.setEnabled(false);
        jPanel3.add(txtUser4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 50, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/name_25px.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator6.setForeground(new java.awt.Color(73, 181, 172));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, 10));

        jLabel17.setText("Usuário");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        txtUser6.setBackground(new java.awt.Color(255, 255, 255));
        txtUser6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUser6.setForeground(new java.awt.Color(73, 181, 172));
        txtUser6.setBorder(null);
        jPanel3.add(txtUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 270, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8_Lock_25px.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(73, 181, 172));
        jSeparator7.setForeground(new java.awt.Color(73, 181, 172));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 10));

        jLabel19.setText("Password");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel20.setText("Código");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel21.setText("Farmacéutico");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        uJComboBox3.setBackground(new java.awt.Color(255, 255, 255));
        uJComboBox3.setForeground(new java.awt.Color(73, 181, 172));
        uJComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        jPanel3.add(uJComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 300, 30));

        jLabel22.setText("Cargo");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        uJComboBox4.setBackground(new java.awt.Color(255, 255, 255));
        uJComboBox4.setForeground(new java.awt.Color(73, 181, 172));
        uJComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Farmaceutico", "Administrador" }));
        jPanel3.add(uJComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 300, 30));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "Expresso POS", "Kenya", null, null},
                {null, "ROM Gen", "US", null, null},
                {null, "Text Ed", "UK", null, null},
                {null, "Mola Con", "China", null, null}
            },
            new String [] {
                "ID", "Usuário", "Farmacéutico", "Cargo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(22);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(30);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 710, 180));

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/edit_25px.png"))); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnEditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 95, 35));

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel_25px.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 95, 35));

        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/new_25px.png"))); // NOI18N
        btnNovo1.setText("Novo");
        btnNovo1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNovo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnNovo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, 95, 35));

        btnSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/save_25px.png"))); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnSalvar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 95, 35));

        btnRemover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_25px.png"))); // NOI18N
        btnRemover1.setText("Remover");
        btnRemover1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRemover1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnRemover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 95, 35));

        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/menu_25px.png"))); // NOI18N
        btnMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenu1MouseClicked(evt);
            }
        });
        jPanel3.add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 26));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(73, 181, 172));
        txtPassword.setBorder(null);
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 270, 30));

        jLabel23.setText("Status");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        uJComboBox5.setBackground(new java.awt.Color(255, 255, 255));
        uJComboBox5.setForeground(new java.awt.Color(73, 181, 172));
        uJComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Habilitado", "Desabilitado" }));
        jPanel3.add(uJComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 300, 30));

        frameUsuario.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 770, 600));

        desktopFarmaceutico.add(frameUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, -20, 960, 640));

        pnlBody.add(desktopFarmaceutico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 760, 600));

        getContentPane().add(pnlBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        // TODO add your handling code here:
            dispose();
    }//GEN-LAST:event_btnSairMousePressed

    private void btnMinimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMousePressed
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarMousePressed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        moverRightLeft();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void lblCadFarmaceuticoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFarmaceuticoMouseMoved
        // TODO add your handling code here:
        lblCadFarmaceutico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblCadFarmaceuticoMouseMoved

    private void lblCadFarmaceuticoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFarmaceuticoMouseExited
        // TODO add your handling code here:
        lblCadFarmaceutico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblCadFarmaceuticoMouseExited

    private void lblCadUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseMoved
        // TODO add your handling code here:
        lblCadUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_lblCadUsuarioMouseMoved

    private void lblCadUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseExited
        // TODO add your handling code here:
        lblCadUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_lblCadUsuarioMouseExited

    private void btnMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenu1MouseClicked
        // TODO add your handling code here:
        moverRightLeft();
    }//GEN-LAST:event_btnMenu1MouseClicked

    private void lblCadFarmaceuticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadFarmaceuticoMouseClicked
        // TODO add your handling code here:
        this.frameFarmaceutico.setVisible(true);
        this.frameUsuario.setVisible(false);
        slideFrames();
    }//GEN-LAST:event_lblCadFarmaceuticoMouseClicked

    private void lblCadUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadUsuarioMouseClicked
        // TODO add your handling code here:
        this.frameFarmaceutico.setVisible(false);
        this.frameUsuario.setVisible(true);
    }//GEN-LAST:event_lblCadUsuarioMouseClicked

    int xx, xy;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void frameFarmaceuticoInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_frameFarmaceuticoInternalFrameOpened
        // TODO add your handling code here:
        this.txtMasculino.setSelected(true);
        sexo = "Masculino";
    }//GEN-LAST:event_frameFarmaceuticoInternalFrameOpened

    private void txtMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasculinoActionPerformed
        // TODO add your handling code here:
        sexo = "Masculino";
    }//GEN-LAST:event_txtMasculinoActionPerformed

    private void txtFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFemeninoActionPerformed
        // TODO add your handling code here:
        sexo = "Femenino";
    }//GEN-LAST:event_txtFemeninoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // TODO add your handling code here:
            saveFarmaceutico();
        } catch (SQLException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSelectImagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectImagActionPerformed
        // TODO add your handling code here:
        JFileChooser arquivo = new JFileChooser();
        int janela = arquivo.showOpenDialog(null);
        if (janela == JFileChooser.APPROVE_OPTION) {
            File file = arquivo.getSelectedFile();
            this.txtImagen.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(this.txtImagen.getText());
            foto = foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            this.lblFoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnSelectImagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }
    
    private void saveFarmaceutico() throws SQLException {
        // FileInputStream arquivoFoto;
        modelFarmaceutico.setNomeCompleto(this.txtNomeCompleto.getText());
        modelFarmaceutico.setTelefone(Integer.parseInt(this.txtTelefone.getText()));
        modelFarmaceutico.setEmail(this.txtEmail.getText());
        modelFarmaceutico.setSexo(sexo);
        modelFarmaceutico.setEstadoCivil(this.txtEstadoCivil.getSelectedItem().toString());
        //modelFarmaceutico.setNomeCompleto(this.txtNomeCompleto.getText());
        try {
            modelFarmaceutico.setAnoNasc(convertDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        modelFarmaceutico.setStatusFarmaceutico(this.txtStatus.getSelectedItem().toString());
        modelFarmaceutico.setCaminhoImage(this.txtImagen.getText());
        try {
            arquivoFoto = new FileInputStream(this.txtImagen.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        // modelFarmaceutico.setImagen(pst.setBinaryStream(10, arquivoFoto));
        //pst.setBinaryStream(10, arquivoFoto);
        if (controllerFarmaceutico.saveFarmaceuticoController(modelFarmaceutico) > 0) {
            JOptionPane.showMessageDialog(this, "Registo salvo com sucesso");
        } else {
            JOptionPane.showMessageDialog(this, "Registo não savo, Verifique novamente");
        }
    }
    
    // modelVenda.setData_Venda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
    
    private void moverRightLeft() {
        AnimationClass lblCadUsuarioRight = new AnimationClass();
        lblCadUsuarioRight.jLabelXRight(-40, 10, 10, 5, this.lblCadUsuario);

        AnimationClass lblCadUsuarioLeft = new AnimationClass();
        lblCadUsuarioLeft.jLabelXLeft(10, -40, 10, 5, this.lblCadUsuario);

        AnimationClass lblCadFarmaceuticoRight = new AnimationClass();
        lblCadFarmaceuticoRight.jLabelXRight(-40, 10, 10, 5, this.lblCadFarmaceutico);

        AnimationClass lblCadFarmaceuticoLeft = new AnimationClass();
        lblCadFarmaceuticoLeft.jLabelXLeft(10, -40, 10, 5, this.lblCadFarmaceutico);

        /*AnimationClass lblProdutoRight = new AnimationClass();
        lblProdutoRight.jLabelXRight(-40, 10, 10, 5, this.lblProduto);

        AnimationClass lblProdutoLeft = new AnimationClass();
        lblProdutoLeft.jLabelXLeft(10, -40, 10, 5, this.lblProduto);*/
    }
    
    public void slideFrames(){
        new Thread(new Runnable() {
            @Override
            public void run() {
                int nb = 0;
                try{
                    while(true){
                        switch(nb){
                            case 0:
                                Thread.sleep(300);
                                ac.jLabelXLeft(800, 390, 12, 10, lblEstadoCivil);
                                ac.jLabelXLeft(800, 390, 12, 10, lblEstadoUsuario);
                                ac.jLabelXLeft(800, 390, 12, 10, lblAnoNascimento);
                           
                                ac.jLabelXRight(-230, 60, 12, 10, lblNomeCompleto);
                                ac.jLabelXRight(-190, 60, 12, 10, lblTelefone);
                                ac.jLabelXRight(-170, 60, 12, 10, lblEmail);
                                ac.jLabelXRight(-170, 60, 12, 10, lblSexo);
                                /*ac.jLabelXRight(-600, 60, 12, 10, jLabel31);
                                ac.jLabelXRight(-500, 80, 12, 10, jLabel26);
                                ac.jLabelXRight(-200, 80, 12, 10, jLabel28);
                                ac.jLabelXRight(-300, 80, 12, 10, jLabel29);
                                ac.jLabelXRight(-320, 80, 12, 10, jLabel27);
                                ac.jLabelXRight(-550, 80, 12, 10, jLabel30);*/
                        }
                    }
                }catch(Exception ex){
                    
                }
            }
        }){
            
        }.start();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JLabel btnMenu1;
    private javax.swing.JLabel btnMinimizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRemover1;
    private javax.swing.JLabel btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSelectImag;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane desktopFarmaceutico;
    private javax.swing.JInternalFrame frameFarmaceutico;
    private javax.swing.JInternalFrame frameUsuario;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAnoNascimento;
    private javax.swing.JLabel lblCadFarmaceutico;
    private javax.swing.JLabel lblCadUsuario;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblEstadoUsuario;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JTable showFarmaceutico;
    private javax.swing.JTextField txtAnoNasc;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmail;
    private componentes.UJComboBox txtEstadoCivil;
    private javax.swing.JRadioButton txtFemenino;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JRadioButton txtMasculino;
    private javax.swing.JTextField txtNomeCompleto;
    private javax.swing.JPasswordField txtPassword;
    private componentes.UJComboBox txtStatus;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUser4;
    private javax.swing.JTextField txtUser6;
    private componentes.UJComboBox uJComboBox3;
    private componentes.UJComboBox uJComboBox4;
    private componentes.UJComboBox uJComboBox5;
    // End of variables declaration//GEN-END:variables
}
